services:
  z-way-server:
    build:
      context: .
    container_name: z-way-container
    devices:
      - /dev/ttyAMA10:/dev/ttyAMA10 # For Z-Wave UZB Stick or Z-Station
#      - /dev/ttyUSB1:/dev/ttyUSB1 # For additional interface like a Z-Station or ZigBee stick
    ports:
      - "8083:8083"
    volumes:
      - ./data:/data
    restart: unless-stopped
